### ISSUE TITLE
Some trimming examples do not run.

### ISSUE THREAD

**Issue by virtualritz** [orbingol/NURBS-Python_Examples#4] opened 2019-11-23 17:05 UTC
The error is always the same. I installed NURBS-Python with pip3.

```bash
> python3 trim_single.py
Traceback (most recent call last):
  File "trim_single.py", line 15, in <module>
    from geomdl.shapes import analytic
ModuleNotFoundError: No module named 'geomdl.shapes'
```

**Comment by orbingol** [comment] 2019-11-25 00:45
Some examples depend on an extension module called `geomdl-shapes`. You can install it via `pip install geomdl.shapes`.

**Comment by virtualritz** [comment] 2019-11-25 12:08
`geomdl-shapes` was already installed by `pip` when I installed `geomdl`:
```bash
> pip3 install geomdl-shapes
Collecting geomdl-shapes
  Downloading https://files.pythonhosted.org/packages/bd/a7/a1a44d5d41aece0b8c0bff378c647f2a8cdced3223603213d0bfe01a57e1/geomdl.shapes-1.3.0-py2.py3-none-any.whl
Requirement already satisfied: geomdl>=5.2.0 in /Users/moritz/Library/Python/3.7/lib/python/site-packages (from geomdl-shapes) (5.2.9)
Installing collected packages: geomdl-shapes
Successfully installed geomdl-shapes```

I still have the same error. `geomdl` is found but `geomdl.shapes` isn't. 

Looking into the resp. folder, it's not there.
```bash
> ls -l /Users/moritz/Library/Python/3.7/lib/python/site-packages
total 0
drwxr-xr-x  41 moritz  staff  1312 Nov 23 16:51 geomdl
drwxr-xr-x   8 moritz  staff   256 Nov 23 16:51 geomdl-5.2.9.dist-info
```

My best guess is that the `pip` package metadata for `geomdl` specifies that is contains/satisfies `geomdl-shapes` while it actually doesn't.

**Comment by orbingol** [comment] 2019-11-25 13:53
I see that you are using MacOS. I don't have a Mac, so I can't reproduce and debug the error. However, I can suggest using Docker containers. Here is the doc page for the NURBS-Python Docker Containers: https://nurbs-python.readthedocs.io/en/latest/install.html#docker-containers

Here is the Docker Hub page: https://hub.docker.com/r/idealabisu/nurbs-python

I have tested the simple module import on Docker after a fresh pull. It seems to work fine:

```
nurbs@e1f71a7d7923:~$ python
Python 3.7.4 (default, Aug 14 2019, 12:19:22)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geomdl
>>> import geomdl.shapes
>>> geomdl.shapes.__file__
'/home/nurbs/.local/lib/python3.7/site-packages/geomdl/shapes/__init__.py'
```

I have also tested with a clean conda environment on Windows (with [Miniconda](https://docs.conda.io/en/latest/miniconda.html)) and it seems to work fine too:

```
(base) C:\>conda activate testpy37

(testpy37) C:\>pip install geomdl.shapes
Collecting geomdl.shapes
  Downloading https://files.pythonhosted.org/packages/bd/a7/a1a44d5d41aece0b8c0bff378c647f2a8cdced3223603213d0bfe01a57e1/geomdl.shapes-1.3.0-py2.py3-none-any.whl
Collecting geomdl>=5.2.0
  Downloading https://files.pythonhosted.org/packages/b0/95/38152ca47b749553d2ff93fe2ad6cbe9d724ced152c0a48b5ba2a13a3f83/geomdl-5.2.9-py2.py3-none-any.whl (147kB)
     |████████████████████████████████| 153kB 2.2MB/s
Installing collected packages: geomdl, geomdl.shapes
Successfully installed geomdl-5.2.9 geomdl.shapes-1.3.0

(testpy37) C:\>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import geomdl.shapes
>>> from geomdl.shapes import analytic
>>> dir(analytic)
['AnalyticGeometry', 'Circle', 'Freeform', 'Rectangle', 'Sphere', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'abc', 'abstract', 'add_metaclass', 'export', 'freeform', 'linalg', 'math']
>>> ^Z
```

**Comment by orbingol** [comment] 2019-11-26 17:51
I am closing this issue for now. Please let me know if you need more help.

**Closed by orbingol** 2019-11-26 17:51 UTC
